name: newsapp
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  animated_splash: ^1.0.0
  gradient_text: ^1.0.2
  simple_share: ^0.0.1+4
  file_picker: ^1.4.3+2
  flutter_swiper: ^1.1.6
  url_launcher: ^5.4.1
  flutter_slidable: ^0.5.4
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1
  connectivity: ^0.4.6+1
  http: ^0.12.0+3
  flutter_offline: ^0.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/network.gif
    - assets/walk1.png
    - assets/walk2.png
    - assets/walk3.png
    - assets/i1.png
    - assets/i2.png
    - assets/i3.png
    - assets/Bookmark.png
    - assets/feedback.png
    - assets/news.png
    - assets/offline.png
    - assets/Feedback.gif
    - assets/act1.png
    - assets/act2.png
    - assets/act3.png
    - assets/act4.png
    - assets/act5.png
    - assets/act6.png
    - assets/act7.png
    - assets/act8.png
    - assets/hindi.png
    - assets/hollywood.png
    - assets/malayalam.png
    - assets/telgu.png
    - assets/tamil.png
    - assets/kannada.png
   



